easy_admin:
   site_name: 'Bellybutton' 
   design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
   entities:
    Article:
      class: App\Entity\Article
      form:
        fields:
          - {property: 'title'}
          - {property: 'subtitle'}
          - {property: 'body', type: 'fos_ckeditor', type_options: { config_name: 'main_config' }}
          - {property: 'imageFile', type: 'file'}
          - {property: 'status'}
          - {property: 'tags'}
    Commentary:
      class: App\Entity\Commentary
      form:
        fields:
          - {property: 'username'}
          - {property: 'body'}
          - {property: 'article'}
    Tag:
      class: App\Entity\Tag
      form:
        fields:
          - {property: 'name'}
    User:
      class: App\Entity\User
      form:
        fields:
          - {property: 'email'}
          - {property: 'lastname'}
          - {property: 'status'}
          - {property: 'userRoles'}
          - {property: 'idInstagram'}
          - {property: 'idFacebook'}
          - {property: 'idYoutube'}
          - {property: 'idSnapchat'}
          - {property: 'idTiktok'}
    Role:
      class: App\Entity\Role
      form:
        fields:
          - {property: 'name'}
          - {property: 'label'}
    Campaign:
      class: App\Entity\Campaign
      form:
        fields:
          - {property: 'name'}
          - {property: 'price'}
          - {property: 'viewGoal'}
          - {property: 'view'}
          - {property: 'nbLike'}
          - {property: 'nbComment'}
          - {property: 'totalImpression'}
          - {property: 'costPerThousand'}
          - {property: 'engagementRate'}
          - {property: 'status'}
          - {property: 'finishAt'}
          - {property: 'createdAt'}
    Support:
      class: App\Entity\Support
      form:
        fields:
          - {property: 'name'}
          - {property: 'idVideo'}
          - {property: 'network'}
          - {property: 'createdAt'}
          - {property: 'campaign'}
    View:
      class: App\Entity\View
      form:
        fields:
          - {property: 'number'}
          - {property: 'createdAt'}
          - {property: 'support'}
    Comment:
      class: App\Entity\Comment
      form:
        fields:
          - {property: 'number'}
          - {property: 'createdAt'}
          - {property: 'support'}
    Like:
      class: App\Entity\Like
      form:
        fields:
          - {property: 'number'}
          - {property: 'createdAt'}
          - {property: 'support'}
