vich_uploader:
    db_driver: orm

    mappings:
       blog_image:
           uri_prefix: /assets/blog/images
           upload_destination: '%kernel.project_dir%/public/assets/blog/images'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
